version: '3.8'

services:
  crm:
    build:
      context: ./
    command: ["python3", "main.py"]
    volumes:
      - ./crm:/app

  erp:
    build:
      context: ./
    command: ["python3", "main.py"]
    volumes:
      - ./erp:/app

  wms:
    build:
      context: ./
    command: ["python3", "main.py"]
    volumes:
      - ./wms:/app

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - crm
      - erp
      - wms
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
